#server config
server:
  port: 5012
  servlet:
    context-path: /Oracle-Service

### TODO. optimization
group-channel-connections-configs:
  configs:
#    - caCert: classpath:ca.crt
#      sslCert: classpath:node.crt
#      sslKey: classpath:node.key
#      chainId: 1
#      all-channel-connections:
#         - group-id: 1 #group ID
#           connections-str:
#              - 119.23.46.126:20200 # node listen_ip:channel_listen_port
#    - caCert: classpath:ca.crt
#      sslCert: classpath:node.crt
#      sslKey: classpath:node.key
#      chainId: 2
#      all-channel-connections:
#         - group-id: 1 #group ID
#           connections-str:
#              - 127.0.0.1:20200 # node listen_ip:channel_listen_port
# sdk
sdk:
  orgName: orgTest
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  timeout: 10000
  keepAlive: 60
  encryptType: 0 #0:standard, 1:guomi

#key store
key-user:
  store_file: "./key/keyStoreUser.txt"  # file to save keyUser.

### TODO. optimization
#event register,
#fisco-bcos 2.2 or latest
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id14
#event:
#  eventRegisters:
#    - chainId: 2
#      group: 1
#      contractAddress: ""
#      fromBlock: "latest"
#      toBlock: "latest"
#
#    - chainId: 1
#      group: 1
#      contractAddress: "0x8fcd8a0db3d335c5ef6fe3a4940875adb13eb789"
#      fromBlock: "latest"
#      toBlock: "latest"

#log config
logging:
  config: classpath:log4j2.xml
  level.com.webank.oracle: info

# constant
constant:
  transMaxWait: 30
  restTemplateMaxWait: 30

spring:
  profiles:
    active: dev
