#server config
server:
  port: 5012
  servlet:
    context-path: /Oracle-Service
  config:
    # 服务版本
    version: v0.5.0

########################################################################
# 配置 TrustOracle 连接的链和群组信息（证书和地址）:
#   1. 同一条链可以配置多个群组
#   2. 可以配置多条链
########################################################################
group-channel-connections-configs:
  configs:
    ## 第一条链的连接信息，证书，群组列表和 IP:Port
    - chainId: 1
      caCert: classpath:1/ca.crt
      sslCert: classpath:1/node.crt
      sslKey: classpath:1/node.key
      all-channel-connections:
         - group-id: 1
           connections-str:
             # node listen_ip:channel_listen
             - 127.0.0.1:20200
        ## 群组 2 的信息
        #- group-id: 2
        #  connections-str:
        #    - 127.0.0.1:20200

    ## 第二条链的连接信息，证书，群组列表以及对应的 IP:Port
    #- chainId: 2
    #  caCert: classpath:2/ca.crt
    #  sslCert: classpath:2/node.crt
    #  sslKey: classpath:2/node.key
    #  all-channel-connections:
    #    - group-id: 1
    #      connections-str:
    #        - 127.0.0.1:20200




#fisco-bcos 2.2 or latest
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id14
########################################################################
# 配置事件监听：
#   1. 配置 TrustOracle 需要监听的链（ChainId）和群组（groupId）
#   2. 配置的 chainId 和 groupId 需要配置在 group-channel-connections-configs
########################################################################
event:
  eventRegisters:
   # list of EventRegister objects. Use default value when property not configured.
   # Oracle contracts will be auto deployed when contractAddress is blank
   - {chainId: 1, group: 1, operator: "operator1", url: "http://localhost1"}
   #- {chainId: 1, group: 2, operator: "operator2", url: "http://localhost2"}
   #- {chainId: 2, group: 1, operator: "operator3", url: "http://localhost3·"}
   #- {chainId: 2, group: 2, operator: "operator4", url: "http://localhost4"}

# sdk
sdk:
  orgName: orgTest
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  timeout: 10000
  keepAlive: 60
  encryptType: 0 #0:standard, 1:guomi

#key store
key-user:
  store_file: "./key/ECC/keyStoreUser.txt"  # file to save keyUser.

#log config
logging:
  config: classpath:log4j2.xml
  level.com.webank.oracle: info

# constant
constant:
  transMaxWait: 30
  restTemplateMaxWait: 30

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trustoracle?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: "defaultAccount"
    password: "defaultPassword"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    openInView: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      session:
        events:
          log: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
