
### TODO. optimization
group-channel-connections-configs:
  configs:
    - caCert: classpath:ca.crt
      sslCert: classpath:node.crt
      sslKey: classpath:node.key
      chainId: 1
      all-channel-connections:
         - group-id: 1 #group ID
           connections-str:
              - 119.23.46.126:20200 # node listen_ip:channel_listen_port
#    - caCert: classpath:ca.crt
#      sslCert: classpath:node.crt
#      sslKey: classpath:node.key
#      chainId: 2
#      all-channel-connections:
#         - group-id: 1 #group ID
#           connections-str:
#              - 127.0.0.1:20200 # node listen_ip:channel_listen_port
# sdk

#key store

### TODO. optimization
#event register,
#fisco-bcos 2.2 or latest
#https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#id14
event:
  eventRegisters:
#    - chainId: 2
#      group: 1
#      contractAddress: ""
#      fromBlock: "latest"
#      toBlock: "latest"

    - chainId: 1
      group: 1
      contractAddress: "0x8fcd8a0db3d335c5ef6fe3a4940875adb13eb789"
      fromBlock: "latest"
      toBlock: "latest"


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.248.156:3306/webaseoracle?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: "root"
    password: "xBj2019"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    openInView: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      session:
        events:
          log: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

